int _putchar(char c);
void print_alphabet(void);
void print_alphabet_x10(void);
int _islower(int c);
int _isalpha(int c);
#ifdef main #define main int print_sign(int n) #endif;
#ifdef main #define main int _abs(int) #endif;
#ifdef main #define main int print_last_digit(int) #endif;
#ifdef main #define main void jack_bauer(void) #endif;
#ifdef main #define main void times_table(void) #endif;
#ifdef main #define main int add(int, int) #endif;
#ifdef main #define main void print_to_98(int n) #endif;
#ifdef main #define main void print_times_table(int n) #endif;
