#ifndef main #define main int _putchar(char c) #endif;
#ifndef main #define main void print_alphabet(void) #endif;
#ifndef main #define main void print_alphabet_x10(void) #endif;
#ifndef main #define main int _islower(int c) #endif;
#ifndef main #define main int _isalpha(int c) #endif;
#ifndef main #define main int print_sign(int n) #endif;
#ifndef main #define main int _abs(int) #endif;
#ifndef main #define main int print_last_digit(int) #endif;
#ifndef main #define main void jack_bauer(void) #endif;
#ifndef main #define main void times_table(void) #endif;
#ifndef main #define main int add(int, int) #endif;
#ifndef main #define main void print_to_98(int n) #endif;
#ifndef main #define main void print_times_table(int n) #endif;
